//📝 A este archivo se consulta para elegir los íconos de material icons

const iconsformat = {
  'Despejado': 'mode_night',
  'Soleado': 'light_mode',
  'Parcialmente nublado': 'light',
  'Nublado': 'light',
  'Cielo cubierto': 'light',
  'Neblina': 'light',
  'Lluvia  moderada a intervalos': 'light',
  'Nieve moderada a intervalos en las aproximaciones': 'light',
  'Aguanieve moderada a intervalos en las aproximaciones': 'light',
  'Llovizna helada a intervalos en las aproximaciones': 'light',
  'Cielos tormentosos en las aproximaciones': 'light',
  'Chubascos de nieve': 'light',
  'Ventisca': 'light',
  'Niebla moderada': 'light',
  'Niebla helada': 'light',
  'Llovizna a intervalos': 'light',
  'Llovizna': 'light',
  'Llovizna helada': 'light',
  'Fuerte llovizna helada': 'light',
  'Lluvias ligeras a intervalos': 'light',
  'Ligeras lluvias': 'light',
  'Periodos de lluvia moderada': 'light',
  'Lluvia moderada': 'light',
  'Periodos de fuertes lluvias': 'light',
  'Fuertes lluvias': 'light',
  'Ligeras lluvias heladas': 'light',
  'Lluvias heladas fuertes o moderadas': 'light',
  'Ligeras precipitaciones de aguanieve': 'light',
  'Aguanieve fuerte o moderada': 'light',
  'Nevadas ligeras a intervalos': 'light',
  'Nevadas ligeras': 'light',
  'Nieve moderada a intervalos': 'light',
  'Nieve moderada': 'light',
  'Nevadas intensas': 'light',
  'Fuertes nevadas': 'light',
  'Granizo': 'light',
  'Ligeras precipitaciones': 'light',
  'Lluvias fuertes o moderadas': 'light',
  'Lluvias torrenciales': 'light',
  'Ligeros chubascos de aguanieve': 'light',
  'Chubascos de aguanieve fuertes o moderados': 'light',
  'Ligeras precipitaciones de nieve': 'light',
  'Chubascos de nieve fuertes o moderados': 'light',
  'Ligeros chubascos acompañados de granizo': 'light',
  'Chubascos fuertes o moderados acompañados de granizo': 'light',
  'Intervalos de lluvias ligeras con tomenta en la región': 'light',
  'Lluvias con tormenta fuertes o moderadas en la región': 'light',
  'Nieve moderada con tormenta en la región': 'light',
  'Nieve moderada o fuertes nevadas con tormenta en la región': 'light'
}

export default iconsformat